### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by EtaCassiopeia** [kangpeilun/VastGaussian#17]
Training complete. [01/07 11:54:20]
Merging Partitions... [01/07 11:54:20]
region: ./output/dream_home/point_cloud/iteration_7000/3_1_point_cloud.ply [01/07 11:54:33]
x_min:1.0858807563781738, x_max:inf, z_min:-inf, z_max:-0.6639560461044312 [01/07 11:54:33]
/home/mohsen/anaconda3/envs/vast-gaussian/lib/python3.8/site-packages/matplotlib/patches.py:739: RuntimeWarning: invalid value encountered in scalar add
  y1 = self.convert_yunits(self._y0 + self._height)
/home/mohsen/anaconda3/envs/vast-gaussian/lib/python3.8/site-packages/matplotlib/transforms.py:2050: RuntimeWarning: invalid value encountered in scalar add
  self._mtx[1, 2] += ty
point_cloud_path: ./output/scan001/point_cloud/iteration_7000/3_1_point_cloud.ply  [01/07 11:54:34]
 [01/07 11:54:34]
Traceback (most recent call last):
  File "train_vast.py", line 377, in <module>
    seamless_merge(lp.model_path, point_cloud_dir)
  File "/home/mohsen/code/VastGaussian/seamless_merging.py", line 173, in seamless_merge
    points = np.concatenate(xyz_list, axis=0)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate
/home/mohsen/anaconda3/envs/vast-gaussian/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by kangpeilun** [comment]
You can use meshlab to check the tiling and note that it is a good idea to perform Manhattan alignment before training vastgs

**Comment by gwen233666** [comment]
> 训练完成。[01/07 11:54:20] 合并分区... [01/07 11:54:20] 区域：./output/dream_home/point_cloud/iteration_7000/3_1_point_cloud.ply [01/07 11:54:33] x_min：1.0858807563781738，x_max：inf，z_min：-inf，z_max：-0.6639560461044312 [01/07 11:54:33] /home/mohsen/anaconda3/envs/vast-gaussian/lib/python3.8/site-packages/matplotlib/patches.py:739：RuntimeWarning：标量添加 y1 =中遇到无效值self.convert_yunits(self._y0 + self._height) /home/mohsen/anaconda3/envs/vast-gaussian/lib/python3.8/site-packages/matplotlib/transforms.py:2050: Ru​​ntimeWarning: 在标量添加中遇到无效值 self._mtx[1, 2] += ty point_cloud_path: ./output/scan001/point_cloud/iteration_7000/3_1_point_cloud.ply [01/07 11:54:34] [01/07 11:54:34] Traceback（最近一次调用最后一次）： 文件“train_vast.py”，第 377 行，在 seamless_merge（lp.model_path，point_cloud_dir） 文件“/home/mohsen/code/VastGaussian/seamless_merging.py”，行173，在 seamless_merge 中 points = np.concatenate(xyz_list, axis=0) 文件“< **array_function** internals>”，第 200 行，在 concatenate 中 ValueError: 至少需要一个数组来连接 /home/mohsen/anaconda3/envs/vast-gaussian/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker：关闭时似乎有 1 个泄漏的信号量对象需要清理 warnings.warn('resource_tracker：似乎有 %d '

Hello, have you solved it yet？

**Comment by HaoRayx** [comment]
hello , I have met the same problem.Did you solved it?
