### ISSUE TITLE
Can you show the program environment

### ISSUE THREAD

**Issue by HuChengang** [kangpeilun/VastGaussian#28]
我在试着运行您的程序遇见了环境问题：
(vastgaussian) F:\VastGaussian>python train_vast.py -s data\castle3
Traceback (most recent call last):
  File "F:\VastGaussian\train_vast.py", line 19, in <module>
    from gaussian_renderer import render, network_gui
  File "F:\VastGaussian\gaussian_renderer\__init__.py", line 14, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
  File "C:\Users\Administrator\anaconda3\envs\vastgaussian\lib\site-packages\diff_gaussian_rasterization\__init__.py", line 15, in <module>
    from . import _C
ImportError: DLL load failed while importing _C: 找不到指定的程序。
可以展示一下你的运行环境吗？
I'm trying to run your program and I'm having problems. Can you show me your running environment?

**Comment by 92401** [comment]
Have you solved the problem, please?
