### ISSUE TITLE
Error when running render.py

### ISSUE THREAD

**Issue by Sanctuary345** [kangpeilun/VastGaussian#40]
When I run render.py, the following error is reported.
Traceback (most recent call last):
  File "/storage/public/home/2022032005/PycharmProject/VastGaussian-refactor/VastGaussian-refactor/render.py", line 85, in <module>
    render_sets(model.extract(args), args.load_iteration, pipeline.extract(args), args.skip_train, args.skip_test)
  File "/storage/public/home/2022032005/PycharmProject/VastGaussian-refactor/VastGaussian-refactor/render.py", line 44, in render_sets
    scene = Scene_Eval(dataset, gaussians, args.load_iteration)
  File "/storage/public/home/2022032005/PycharmProject/VastGaussian-refactor/VastGaussian-refactor/scene/__init__.py", line 200, in __init__
    scene_info = sceneLoadTypeCallbacks["ColmapEval"](args.source_path, args.images, args.man_trans, args.model_path)
  File "/storage/public/home/2022032005/PycharmProject/VastGaussian-refactor/VastGaussian-refactor/scene/dataset_readers.py", line 386, in readColmapSceneInfoEval
    nerf_normalization = getNerfppNorm(test_cam_infos)
  File "/storage/public/home/2022032005/PycharmProject/VastGaussian-refactor/VastGaussian-refactor/scene/dataset_readers.py", line 63, in getNerfppNorm
    center, diagonal = get_center_and_diag(cam_centers)
  File "/storage/public/home/2022032005/PycharmProject/VastGaussian-refactor/VastGaussian-refactor/scene/dataset_readers.py", line 49, in get_center_and_diag
    cam_centers = np.hstack(cam_centers)
  File "/storage/public/home/2022032005/miniconda3/envs/cf_3dgs/lib/python3.10/site-packages/numpy/core/shape_base.py", line 359, in hstack
    return _nx.concatenate(arrs, 1, dtype=dtype, casting=casting)
ValueError: need at least one array to concatenate

How can I solve it?

**Comment by Sanctuary345** [comment]
I set eval to True during training and render, and it doesn't report the above error when I run render.py.
