### ISSUE TITLE
 Error：partition

### ISSUE THREAD

**Issue by Sanctuary345** [kangpeilun/VastGaussian#41]
I've found that I don't report a bit of an error when I run my own dataset with a 3x3 partition. Entering any other partition reports the following error.
Traceback (most recent call last):
  File "/storage/public/home/2022032005/PycharmProject/VastGaussian-refactor/VastGaussian-refactor/train_vast.py", line 321, in <module>
    partition_num, partition_id_list = data_partition(lp)
  File "/storage/public/home/2022032005/PycharmProject/VastGaussian-refactor/VastGaussian-refactor/utils/partition_utils.py", line 30, in data_partition
    DataPartitioning = ProgressiveDataPartitioning(scene_info, all_cameras, lp.model_path,
  File "/storage/public/home/2022032005/PycharmProject/VastGaussian-refactor/VastGaussian-refactor/scene/vastgs/data_partition.py", line 64, in __init__
    self.run_DataPartition(train_cameras)
  File "/storage/public/home/2022032005/PycharmProject/VastGaussian-refactor/VastGaussian-refactor/scene/vastgs/data_partition.py", line 102, in run_DataPartition
    partition_list = self.Position_based_data_selection(partition_dict, refined_ori_bbox)
  File "/storage/public/home/2022032005/PycharmProject/VastGaussian-refactor/VastGaussian-refactor/scene/vastgs/data_partition.py", line 356, in Position_based_data_selection
    ori_point_bbox=self.get_point_range(points),
  File "/storage/public/home/2022032005/PycharmProject/VastGaussian-refactor/VastGaussian-refactor/scene/vastgs/data_partition.py", line 297, in get_point_range
    return [min(x_list), max(x_list),
ValueError: min() arg is an empty sequence
How do I fix it?

**Comment by Zqzne** [comment]
same problem, have you solved it?
