### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by Mr-DG** [kangpeilun/VastGaussian#46]
Traceback (most recent call last):
  File "D:\sofeware\anaconda3\envs\3dgs\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\sofeware\anaconda3\envs\3dgs\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "E:\jupyter_base\VastGaussian\train_vast.py", line 177, in parallel_local_training
    training(lp_args, op_args, pp_args, test_iterations, save_iterations, checkpoint_iterations,start_checkpoint, debug_from, logger=logger)
  File "E:\jupyter_base\VastGaussian\train_vast.py", line 50, in training
    scene = PartitionScene(dataset, gaussians)
  File "E:\jupyter_base\VastGaussian\scene\__init__.py", line 119, in __init__
    scene_info = sceneLoadTypeCallbacks["ColmapVast"](args.source_path, args.partition_model_path,
  File "E:\jupyter_base\VastGaussian\scene\dataset_readers.py", line 354, in readColmapSceneInfoVast
    nerf_normalization = getNerfppNorm(train_cam_infos)  # 使用找到在世界坐标系下相机的几何中心
  File "E:\jupyter_base\VastGaussian\scene\dataset_readers.py", line 63, in getNerfppNorm
    center, diagonal = get_center_and_diag(cam_centers)
  File "E:\jupyter_base\VastGaussian\scene\dataset_readers.py", line 49, in get_center_and_diag
    cam_centers = np.hstack(cam_centers)
  File "D:\sofeware\anaconda3\envs\3dgs\lib\site-packages\numpy\core\shape_base.py", line 359, in hstack
    return _nx.concatenate(arrs, 1, dtype=dtype, casting=casting)
ValueError: need at least one array to concatenate
如果解决这个报错呢

**Comment by 92401** [comment]
please tell me your input information.

**Comment by Next11111** [comment]
python train_vast.py -s ../datasets/urban_scene_3d/residence/ --exp_name residence --manhattan --platform tj --pos "0 0 0" --rot "180 30 0" --llffhold 83 --resolution 4 --m_region 5 --n_region 5 --iterations 60_000

**Comment by huitailang2001** [comment]
> 回溯（最近一次调用最后）：文件“D：\sofeware\anaconda3\envs\3dgs\lib\multiprocessing\process.py”，第 314 行，_bootstrap self.run（） 文件“D：\sofeware\anaconda3\envs\3dgs\lib\multiprocessing\process.py”，第 108 行，在运行 self._target（*self._args， **self._kwargs） 文件 “E：\jupyter_base\VastGaussian\train_vast.py”， 第 177 行， parallel_local_training训练中（lp_args， op_args， pp_args， test_iterations， save_iterations， checkpoint_iterations，start_checkpoint， debug_from， logger=logger） 文件 “E：\jupyter_base\VastGaussian\train_vast.py”，第 50 行，在训练场景中 = PartitionScene（dataset， gaussians） 文件 “E：\jupyter_base\VastGaussian\scene__init__.py”， 第 119 行，**init** scene_info = sceneLoadTypeCallbacks[“ColmapVast”]（args.source_path， args.partition_model_path， 文件 “E：\jupyter_base\VastGaussian\scene\dataset_readers.py”， 第 354 行， in readColmapSceneInfoVast nerf_normalization = getNerfppNorm（train_cam_infos） # 使用找到在世界坐标系下相机的几何中心 文件 “E：\jupyter_base\VastGaussian\scene\dataset_readers.py”， 第 63 行， 在 getNerfppNorm 中心， 对角线 = get_center_and_diag（cam_centers） 文件 “E：\jupyter_base\VastGaussian\scene\dataset_readers.py”，第 49 行，get_center_and_diag cam_centers = np.hstack（cam_centers） 文件 “D：\sofeware\anaconda3\envs\3dgs\lib\site-packages\numpy\core\shape_base.py”，第 359 行，在 hstack 中 return _nx.concatenate（arrs， 1， dtype=dtype， casting=casting） ValueError： need at least one array to concatenate 如果解决这个报错呢

请问这个问题你解决了吗？我也遇到了这个问题

**Comment by 92401** [comment]
This could be a problem with your Manhattan rotation matrix.

**Comment by 92401** [comment]
This error message indicates that you have a problem reading the cameras, you can print the list of cameras to see if it is empty

**Comment by huitailang2001** [comment]
> 这可能是您的曼哈顿轮换矩阵的问题。

谢谢你的回答。之前尝试用threejs出现了这个问题，后来就用cloudcompare了，但最后的A不是4*4的矩阵吗，但是输入是3*3呀，这个具体怎么操作呢，谢谢，有点困扰。

**Comment by 92401** [comment]
If you're confused about the dimensions of the Manhattan output matrix, you can check out manhattan_utils.py

**Comment by huitailang2001** [comment]
> 如果您对 Manhattan 输出矩阵的维度感到困惑，可以查看 manhattan_utils.py

好的，谢谢你的回复，我继续试试。

**Comment by huitailang2001** [comment]
> 如果您对 Manhattan 输出矩阵的维度感到困惑，可以查看 manhattan_utils.py

可以帮我看看我之前采用的threejs方法对不对吗？图片如下（![Image](https://github.com/user-attachments/assets/5e04def5-2c1f-4840-8d73-d0de3a240a50)）

**Comment by 92401** [comment]
我想看看您的 python 命令

**Comment by huitailang2001** [comment]
> 我想看看您的 python 命令

command = (f'python train_vast.py -s data/phantom3-ieu --exp_name phantom3-ieu-no'
           f' --eval'
           f' --llffhold 70 --resolution 1'
           f' --manhattan --platform tj --pos "0.000 0.000 0.000" --rot "90.000 0.000 0.000"'
           f' --m_region 2 --n_region 2'
           f' --iterations 30_000')指令是这样的，麻烦帮忙看看

**Comment by 92401** [comment]
请你在readColmapSceneInfoVast函数中，这条代码前nerf_normalization = getNerfppNorm(train_cam_infos)打印print(train_cam_infors)

**Comment by huitailang2001** [comment]
> 请你在readColmapSceneInfoVast函数中，这条代码前nerf_normalization = getNerfppNorm（train_cam_infos）打印print（train_cam_infors）
你好，返回的是一个空列表[],不知道什么原因，可以请教一下吗

**Comment by huitailang2001** [comment]
> 请你在readColmapSceneInfoVast函数中，这条代码前nerf_normalization = getNerfppNorm（train_cam_infos）打印print（train_cam_infors）

求告知原因，真的困扰很久了，谢谢谢谢

**Comment by 92401** [comment]
这表明你的相机未被正确读取，你可以现在colmap中查看相机位姿是否正常，不过这部分一般不会出错，另一个原因就是曼哈顿旋转的问题，如果three.js检查不到问题，你可以试试cloudcompare的曼哈顿旋转。之前我也遇到了同样的问题，于是我代码直接改成了xy平面分区

**Comment by shine157** [comment]
请问你解决了吗，我也是这个问题，不知道该怎么解决

**Comment by shine157** [comment]
可以加我qq号869309640，有偿请教

**Comment by huitailang2001** [comment]
> 这表明你的相机未被正确读取，你可以现在colmap中查看相机位姿是否正常，不过这部分一般不会出错，另一个原因就是曼哈顿旋转的问题，如果three.js检查不到问题，你可以试试cloudcompare的曼哈顿旋转。之前我也遇到了同样的问题，于是我代码直接改成了xy平面分区

改成xy平面分区怎么改呀，可以告知嘛

**Comment by huitailang2001** [comment]
> 这表明你的相机未被正确读取，你可以现在colmap中查看相机位姿是否正常，不过这部分一般不会出错，另一个原因就是曼哈顿旋转的问题，如果three.js检查不到问题，你可以试试cloudcompare的曼哈顿旋转。之前我也遇到了同样的问题，于是我代码直接改成了xy平面分区

非常感谢你的回复，我尝试了一下cloudcompare还是出现了这样的错误。我看到一个评论是这样解决的：I had the same error. In my case it was because Line 40 in utils/partition_utils.py hard codes the image type to be .jpg in the file: partition_point_cloud/visible/*_camera.txt.但是我不太理解具体怎么改正。我看output文件里也有正常的分区显示，不知道为什么一直出现这个错误，真让人心力憔悴

![Image](https://github.com/user-attachments/assets/1ab8170a-5aa9-4bdc-876a-f00668ce6344)

**Comment by soohyoen** [comment]
In utils/partition_utils.py, the image loading logic is hardcoded to use .jpg.
If your dataset contains .png images, this will cause a mismatch and you need to modify the code accordingly.
