### ISSUE TITLE
ValueError: cannot reshape array of size 1 into shape (3,3)

### ISSUE THREAD

**Issue by xvbai0317** [kangpeilun/VastGaussian#9]
2024-06-03 02:34:20.940364: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-03 02:34:21.013904: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/xzj/project/VastGaussian-master/train_vast.py", line 323, in <module>
    train_main()
  File "/home/xzj/project/VastGaussian-master/train_vast.py", line 283, in train_main
    rot = np.array(lp.rot).reshape([3, 3])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 1 into shape (3,3)

用的是tandt_db数据集

**Comment by Livioni** [comment]
请使用[Versions-that-perform-Manhattan-alignment](https://github.com/kangpeilun/VastGaussian/tree/Versions-that-perform-Manhattan-alignment) 分支下的脚本。
问题应该出现在参数传入上

https://github.com/kangpeilun/VastGaussian/blob/586384a1103029cd81966d6cd74a5e8827c7de75/arguments/parameters.py#L60
下面的应该是正确的：
``` python
    parser.add_argument("--pos", nargs=3, type=float, default = (0.0,0.0,0.0))       # 点云平移
    parser.add_argument("--rot", nargs=3, type=float, default = (0.0,0.0,0.0))       # 点云平移
```
@kangpeilun
